### PR TITLE
Add inputSelect inputOrderBy and inputInclude

### PR DESCRIPTION
**Pull request by fortezhuo**
I just make simple patch, refactoring relations.ts, and bump dependencies.
Please review

### CODE REVIEW

**Comment by m1212e** [comment]
Hi, thank you very much for your input! I'll take time to review this throughout the next week or so. Do you have some deadline/is this urgent for you?

**Comment by fortezhuo** [comment]
I think I still can run and build generated files on my local computers and copy them manually. 

So  no worries, I can wait. Please take your time to review 🙏

**Comment by fortezhuo** [comment]
Thanks. And but I found the whereSchema also need to be tweaked. If we need to use combination operator like ```contains, gt, lt, etc``` the current where schema still not supported. I still dev this feature, and tested it.. if it's ready, I will make another PR. 
https://www.prisma.io/docs/orm/prisma-client/queries/filtering-and-sorting

**Comment by m1212e** [comment]
I've implemented simplified models to validate the other query options you requested in the latest release. I took some inspiration from you PR but ultimately decided to implemet it on the main. Feel free to take a look and close/fork if you want to!

**Comment by fortezhuo** [comment]
I have take a look. And I think I can close this PR. Thanks for implementing it.

**Comment by m1212e** [comment]
Thank you very much for your input!

**Pull request closed without merging**
